V 1.0.1 patches
disorderedmaterials/jv2 pull request #128
Opened 2022-03-29 13:06 UTC by EthanDevlinSTFC

Suite of minor fixes, changes and important functionality implementations.
- Added Larmor to instrument list [closes #123]
- Allowed users to search over run/ date ranges (full validation and plotting compatibility pending) [closes #122] 
- Fixed issue when leaving QInputDialog
- Fix some multi-cycle plotting issues
- Reverse display order of cycles
- Add facilities to set custom heading titles

2022-03-29 14:27 UTC, trisyoungs requested changes
Generally looks OK - couple of small comments.  I tried the mass search across cycles with run numbers (NIMROD, 73450-73549) but it just seemed to hang.  The console gave no evidence of journals being downloaded etc...

2022-03-29 14:27 UTC, trisyoungs commented on backend/isisInternal.py
> +        if field == "start_date":
Shouldn't this be an `else if`? Otherwise the run_number clause can run in addition to the else of the second check.

2022-03-29 14:27 UTC, trisyoungs commented on frontend/mainwindow.cpp
> +    QString textInput = QInputDialog::getText(this, tr("Find"), tr(prompt), QLineEdit::Normal);
This would be nicer as a series of custom `QDialog`s which use controls representing the data types being requested. Eliminates all the incorrect formatting possibilities etc. Probably best left to a follow-up PR given the importance of other stuff in this one.

2022-03-29 14:32 UTC, EthanDevlinSTFC commented on frontend/mainwindow.cpp
> +    QString textInput = QInputDialog::getText(this, tr("Find"), tr(prompt), QLineEdit::Normal);
Definitely agree, I think this requires a custom dialog. This was just a way to get the feature in a functional way out to the users who need it.

2022-03-29 14:48 UTC, EthanDevlinSTFC commented
> I tried the mass search across cycles with run numbers (NIMROD, 73450-73549) but it just seemed to hang. The console gave no evidence of journals being downloaded etc...

This seems peculiar. Just had a go and it worked perfectly in 11 seconds.
The python terminal should print:
"Mass search initiated w/: nimrod run_number 73450-73549"
Then the amount of hits per journal
Then the final elapsed time

Did you get no output at all from python?

2022-03-29 14:53 UTC, trisyoungs commented
> None at all, except for the "no change" message from the ping. I can try again...

"no change" is a debug message from the front-end.
The back-end terminal should give a completion output for every request and debugging outputs in some situations (e.g. mass search).

Could just be a server issue on your end?

2022-03-30 09:48 UTC, trisyoungs commented
Sorry, my bad - was looking at the wrong terminal window!  It's just slow network. We really need the cached database - could be an option on first run to "Download all journal data".  We might need to be a bit careful about how we store it (encryption etc.).

2022-03-30 09:48 UTC, trisyoungs approved these changes

2022-03-30 10:16 UTC, merged