Graph navigation and assorted tidying
disorderedmaterials/jv2 pull request #58
Opened 2022-01-06 16:14 UTC by EthanDevlinSTFC

Created container widget for search elements to tidy code closes #49
Minor bug fix for search label
Creating custom chartview class to enable more detailed and personalised navigation closes #42 

(Discussion over specific graph features and navigation style to be had)

2022-01-06 16:16 UTC, EthanDevlinSTFC commented
Ctrl + F = find, focus on find if open
Ctrl + Shift + F = close find
F3, Shift + F3 = cycle search results

graphing:
Ctrl = hold to toggle zoom dimensions (for rubber band)
arrow keys to move
mouse wheel to zoom
mouse wheel click to reset

2022-01-07 10:15 UTC, trisyoungs requested changes
Search navigation for the run data works really nicely.  Rather than a set of (hidden) controls at the foot of the window, however, I'd rather see this implemented in a more standard way as a modal dialog raised with `Ctrl-F`.  Once a `Find` button is clicked (or a `Select All` button to replicate the functionality of your `searchAll` button) the dialog can close and we then rely just on `F3` and `Shift-F3` for navigation. Displaying the number of search results can then be a job for a permanent widget on the statusbar instead (which at present is sitting there taking up space and not doing anything!

Couple of other observations:
1. I don't seem to have a rubberband zoom at all
2. I like the idea of a middle-mouse click resetting the graph, but it turns out my fingers are used to clicking and holding the middle mouse button to interactively translate the view. This is a feature I implemented in my own graphing stuff, so it isn't what you might call standard, but you could consider going that route as well.

Some other thoughts occurred while I was playing around with the code, which I'll capture as new issues.

2022-01-07 14:08 UTC, EthanDevlinSTFC commented
Strange issue where the rubber band suddenly stopped working. I've reimplemented the way it works so hopefully there won't be another issue there. 
Graph translation on middle click is in, I've prevented the default zoom out on right click because it seems quite bad to me and have used that to replace zoom reset.

2022-01-13 10:13 UTC, trisyoungs reviewed
I think I quite like the separation of the rubberband zoom into x and (Ctrl-) y actions - however, it remains to be seen whether the users will accept it over the more traditional rectangle zoom!

Just a note - this PR doesn't really close #49 since that issue requires taking the search controls off the main UI entirely and putting them in a dialog.

Like where all this is going - some more small things I'll capture as further issues.

2022-01-13 10:13 UTC, trisyoungs commented on frontend/mainwindow.cpp
> +    // SWITCH STATEMENT
I assume this is a "note to self" to convert this to a switch statement. Given that you're checking combinations of keys and modifiers, a set of `if`/`else if`s is probably neater here.

2022-01-13 10:13 UTC, trisyoungs commented on frontend/chartview.cpp
> +        }
I'm sure this is a Qt-related intricacy, but why the need to treat the first middle-click as a special case?

2022-01-13 10:13 UTC, trisyoungs commented on frontend/nexusInteraction.cpp
> +        tabCharts[1]->hide();
Controlling the widgets in this way is valid, but a bit dangerous and hacky and another good reason to have a compound widget and reusable UI file representing all the controls.

2022-01-13 10:42 UTC, EthanDevlinSTFC commented on frontend/mainwindow.cpp
> +    // SWITCH STATEMENT
Noticed this, just forgot to remove the comment

2022-01-13 10:43 UTC, EthanDevlinSTFC commented on frontend/chartview.cpp
> +        }
for the reset to reset scrolling a zoom event needs to occur beforehand. I can remove the zoom from reset and just have it always do on middle click which is cleaner

2022-01-13 10:44 UTC, EthanDevlinSTFC commented on frontend/nexusInteraction.cpp
> +        tabCharts[1]->hide();
Definitely need to get it converted to a compound widget. I think this is best captured as a separate issue.

2022-01-13 21:40 UTC, trisyoungs approved these changes

2022-01-14 15:49 UTC, merged